# ruff.toml
extend-include = ["*.ipynb"]
line-length = 88
indent-width = 2

[format]
indent-style = "space"
quote-style = "single"
line-ending = "auto"

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[lint.isort]
split-on-trailing-comma = false
